name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.2
  cached_network_image: ^3.3.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.8
  intl: any
  json_annotation: ^4.8.1
  logger: ^2.0.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  riverpod_annotation: ^2.1.2
  shared_preferences: ^2.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/hour/
